#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit perplexity youtube weather apps mail google logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--nq" ]]; then
	close_dash && flatpak run com.notepadqq.Notepadqq &

elif [[ "$1" == "--bl" ]]; then
	close_dash && flatpak run org.blender.Blender &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty  --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && dolphin ~ &

elif [[ "$1" == "--ms" ]]; then
	close_dash && kitty -e msfconsole &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--burp" ]]; then
	close_dash && "/home/ishaan/BurpSuiteCommunity/BurpSuiteCommunity" %U &

elif [[ "$1" == "--boxes" ]]; then
	close_dash && flatpak run org.gnome.Boxes &

fi
