#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="firefox --new-tab"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit perplexity youtube weather apps mail google logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://mail.google.com"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--rd" ]]; then
	close_dash && ${cmd} "https://reddit.com"

elif [[ "$1" == "--pr" ]]; then
	close_dash && ${cmd} "https://perplexity.ai"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"
elif [[ "$1" == "--google" ]]; then
	close_dash && ${cmd} "https://google.com"
	
elif [[ "$1" == "--update" ]]; then
	close_dash && hyprctl dispatch exec 'systemupdate.sh up' &


fi
